on:
  push:
  schedule:
    - cron: '0 3 * * 6'


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'

      - name: "Install Dependencies"
        run: |
          go mod download

      - name: "Build"
        run: |
          bin/deploy-compile.sh

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          generate_release_notes: true
          files: target/*
